apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api
type: Opaque
data:
  SQL_USER: ZGJhZG1pbg==
  SQL_PASSWORD: WnNXOERZbXpvVkoyd05BWFdnZGk=
  SQL_SERVER: c3FsLWF6Y29uLWRldi5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: c3FsZGItYXpjb24tZGV2
  