# This is a workflow that creates the four web apps by using bicep code
name: IaC ACR
# This workflow will run on push and on demand
env:
  rgName: ${{ secrets.RESOURCE_GROUP_NAME }}
  rgLocation: ${{ secrets.AZURE_LOCATION }}
  appName: AzCon 
on:
  # Triggers the workflow on push event but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - 'deploy/acr/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 
jobs:
  deployDev:
    name: Deploy to development
    environment: 
      name: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.rgName }} --location ${{ env.rgLocation }}
          echo "Azure resource group created"
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.rgName }}
        template: ./deploy/acr/azure.deploy.bicep
        parameters: applicationName=${{ env.appName }} environment=dev
    - name: getACRcreds
      run: |
        ACRNAME=$(az acr list -g ${{ env.rgName }}| jq -r '.[0] .name')
        ACRLOGINSERVER=$(az acr show -n $ACRNAME | jq -r '.loginServer')
        ACRUSERNAME=$(az acr credential show -n $ACRNAME | jq -r '.username')
        ACRPASSWORD=$(az acr credential show -n $ACRNAME | jq -r '.passwords[0] .value')
        gh auth login --with-token ${{secrets.REPO_ACCESS_TOKEN}}
        gh secret set ACR_NAME -b"$ACRNAME" --org=ms-grcyma --repos="azureconnect"

        

        
